<!doctype html>
<html lang="<?= \F3::get('language'); ?>">
<head>
    <base href="<?= $this->base; ?>" />

    <meta charset="utf-8">

    <title><?= trim(\F3::get('html_title')); ?></title>

    <meta name="description" content="selfoss" />
    <meta name="author" content="Tobias Zeising" />
    <meta name="version" content="<?= \F3::get('version'); ?>" />
    <meta name="referrer" content="no-referrer" />

    <!--  Mobile viewport optimized: j.mp/bplateviewport -->
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1" />

    <!--  Add support for fullscreen Webapp on iPhone 5 -->
    <meta name="viewport" content="initial-scale=1, user-scalable=no, maximum-scale=1" media="(device-height: 568px)" />

    <!-- Web application behavior -->
    <meta name="application-name" content="selfoss" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="mobile-web-app-capable" content="yes" />

    <!-- app tile and notification when adding link to Windows 8 start screen -->
    <meta name="msapplication-TileColor" content="#3d6d69" />
    <meta name="msapplication-square70x70logo" content="<?= $this->base; ?>win8-70-icon.png" />
    <meta name="msapplication-square150x150logo" content="<?= $this->base; ?>win8-150-icon.png" />
    <meta name="msapplication-wide310x150logo" content="<?= $this->base; ?>win8-150-icon.png" />
    <meta name="msapplication-square310x310logo" content="<?= $this->base; ?>win8-310-icon.png" />
    <meta name="msapplication-notification" content="cycle=1; frequency=30; polling-uri=<?= $this->base; ?>win8notifs" />
    <meta name="msapplication-badge" content="frequency=30; polling-uri=<?= $this->base; ?>badge" />

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!--  RSS Feed -->
    <link rel="alternate" type="application/rss+xml" title="RSS Feed" href="feed" />

    <!-- icons -->
    <link rel="apple-touch-icon-precomposed" href="icon-128x128.png" />
    <link rel="icon" type="image/png" href="icon-32x32.png" />
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />

    <!-- Toolbar color from Chrome for Android -->
    <meta name="theme-color" content="#191718" />

    <!-- all css definitions -->
    <?php if (\F3::get('use_system_font') != true) : ?>
        <link rel="stylesheet" href="css/fonts.css" />
    <?php endif; ?>
    <link rel="stylesheet" href="<?= \helpers\View::getGlobalCssFileName(); ?>" />

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <?php

    function vn_to_str ($str){

        $unicode = array(

            'a'=>'á|à|ả|ã|ạ|ă|ắ|ặ|ằ|ẳ|ẵ|â|ấ|ầ|ẩ|ẫ|ậ',

            'd'=>'đ',

            'e'=>'é|è|ẻ|ẽ|ẹ|ê|ế|ề|ể|ễ|ệ',

            'i'=>'í|ì|ỉ|ĩ|ị',

            'o'=>'ó|ò|ỏ|õ|ọ|ô|ố|ồ|ổ|ỗ|ộ|ơ|ớ|ờ|ở|ỡ|ợ',

            'u'=>'ú|ù|ủ|ũ|ụ|ư|ứ|ừ|ử|ữ|ự',

            'y'=>'ý|ỳ|ỷ|ỹ|ỵ',

            'A'=>'Á|À|Ả|Ã|Ạ|Ă|Ắ|Ặ|Ằ|Ẳ|Ẵ|Â|Ấ|Ầ|Ẩ|Ẫ|Ậ',

            'D'=>'Đ|Ð',

            'E'=>'É|È|Ẻ|Ẽ|Ẹ|Ê|Ế|Ề|Ể|Ễ|Ệ',

            'I'=>'Í|Ì|Ỉ|Ĩ|Ị',

            'O'=>'Ó|Ò|Ỏ|Õ|Ọ|Ô|Ố|Ồ|Ổ|Ỗ|Ộ|Ơ|Ớ|Ờ|Ở|Ỡ|Ợ',

            'U'=>'Ú|Ù|Ủ|Ũ|Ụ|Ư|Ứ|Ừ|Ử|Ữ|Ự',

            'Y'=>'Ý|Ỳ|Ỷ|Ỹ|Ỵ',

        );

        foreach($unicode as $nonUnicode=>$uni){

            $str = preg_replace("/($uni)/iu", $nonUnicode, $str);

        }
        $str = str_replace(' ','-',$str);
        $str = mb_strtolower($str);

        return $str;

    }
    ?>
</head>
<body class="
    <?= $this->publicMode === true ? 'publicmode' : ''; ?>
    <?= $this->authEnabled === true ? 'authenabled' : 'loggedin'; ?>
    <?= \F3::get('auto_mark_as_read') == 1 ? 'auto_mark_as_read' : ''; ?>
">

    <div id="message"></div>

    <!-- language settings for jQuery -->
    <span id="lang"
        data-mark="<?= \F3::get('lang_mark'); ?>"
        data-unmark="<?= \F3::get('lang_unmark'); ?>"
        data-star="<?= \F3::get('lang_star'); ?>"
        data-unstar="<?= \F3::get('lang_unstar'); ?>"
        data-source_warn="<?= \F3::get('lang_source_warn'); ?>"
        data-source_saved="<?= \F3::get('lang_source_saved'); ?>"
        data-source_edit="<?= \F3::get('lang_source_edit'); ?>"
        data-reload_list="<?= \F3::get('lang_reload_list'); ?>"
        data-sources_refreshed="<?= \F3::get('lang_sources_refreshed'); ?>"
        data-error_session_expired="<?= \F3::get('lang_error_session_expired'); ?>"
        data-error_add_source="<?= \F3::get('lang_error_add_source'); ?>"
        data-error_delete_source="<?= \F3::get('lang_error_delete_source'); ?>"
        data-error_load_tags="<?= \F3::get('lang_error_load_tags'); ?>"
        data-error_unknown_tag="<?= \F3::get('lang_error_unknown_tag'); ?>"
        data-error_unknown_source="<?= \F3::get('lang_error_unknown_source'); ?>"
        data-error_mark_items="<?= \F3::get('lang_error_mark_items'); ?>"
        data-error_mark_item="<?= \F3::get('lang_error_mark_item'); ?>"
        data-error_star_item="<?= \F3::get('lang_error_star_item'); ?>"
        data-error_logout="<?= \F3::get('lang_error_logout'); ?>"
        data-error_loading="<?= \F3::get('lang_error_loading'); ?>"
        data-error_loading_stats="<?= \F3::get('lang_error_loading_stats'); ?>"
        data-error_saving_color="<?= \F3::get('lang_error_saving_color'); ?>"
        data-error_refreshing_source="<?= \F3::get('lang_error_refreshing_source'); ?>"
        data-error_sync="<?= \F3::get('lang_error_sync'); ?>"
        data-error_invalid_subsection="<?= \F3::get('lang_error_invalid_subsection'); ?>"
        data-seconds="<?= \F3::get('lang_seconds'); ?>"
        data-minutes="<?= \F3::get('lang_minutes'); ?>"
        data-hours="<?= \F3::get('lang_hours'); ?>"></span>

    <!-- other settings -->
    <span id="config"
        data-homepage="<?= (\F3::get('homepage')) ? \F3::get('homepage') : 'newest' ?>"
        data-anonymizer="<?= \helpers\Anonymizer::getAnonymizer(); ?>"
        data-share="<?= \F3::get('share'); ?>"
        data-wallabag="<?= \F3::get('wallabag'); ?>"
        data-wallabag_version="<?= \F3::get('wallabag_version'); ?>"
        data-wordpress="<?= \F3::get('wordpress'); ?>"
        data-auto_mark_as_read="<?= \F3::get('auto_mark_as_read'); ?>"
        data-auto_collapse="<?= \F3::get('auto_collapse'); ?>"
        data-auto_stream_more="<?= \F3::get('auto_stream_more'); ?>"
        data-load_images_on_mobile="<?= \F3::get('load_images_on_mobile'); ?>"
        data-items_perpage="<?= \F3::get('items_perpage'); ?>"
        data-auto_hide_read_on_mobile="<?= \F3::get('auto_hide_read_on_mobile'); ?>"
        data-scroll_to_article_header="<?= \F3::get('scroll_to_article_header'); ?>"
        data-html_title="<?= trim(\F3::get('html_title')); ?>"></span>


    <div id="loginform">
        <form action="<?= $this->base; ?>" method="post">
        <ul id="login">
            <li><h1>selfoss login</h1></li>
            <li><label for="username"><?= trim(\F3::get('lang_login_username')); ?></label> <input type="text" name="username" id="username"></li>
            <li><label for="password"><?= trim(\F3::get('lang_login_password')); ?></label> <input type="password" name="password" id="password"></li>
            <li class="error"></li>
            <li class="button"><label>&nbsp;</label><input type="submit" value="<?= \F3::get('lang_login'); ?>" /></li>
        </ul>
        </form>
    </div>

    <div id="mainui">
        <!-- menu open for smartphone -->
        <div id="nav-mobile">
            <div id="nav-mobile-logo"><span class="unread-count"></span></div>
            <div id="nav-mobile-settings"></div>
        </div>

        <!-- navigation -->
        <div id="nav" role="navigation">
            <div id="nav-logo"></div>

            <hr>

            <div id="nav-tags-wrapper">

                <?php
                    foreach ($this->categories as $category){
                        $id = 'nav-tags-'.vn_to_str($category->name);

                        $html = "<h2 id=\"".$id."\" class=\"nav-tags-collapsed\" tabindex=\"0\" aria-haspopup=\"true\" aria-expanded=\"false\">".$category->name."<span class=\"badge badge-secondary\">".$category->count."</span></h2>
                                    <ul id=\"nav-tags\" style=\"display: none;\">";

                        foreach ($category->rules as $rule){
                            $html .= '<li class="tags">'.$rule->url.'</li>';
                        }

                        $html .= "</ul>";

                        echo $html;

                        $script = "<script>$('#".$id."').unbind('click').click(function(){
                                       $('#".$id." + #nav-tags').slideToggle('slow');
                                       $('#".$id."').toggleClass('nav-tags-collapsed nav-tags-expanded')
                                       .attr('aria-expanded',function(i,attr){
                                           return attr=='true'?'false':'true';
                                       });
                                    });
                                </script>";
                        echo $script;
                    }

                ?>

            </div>

            <hr>
        </div>

        <!-- content -->
        <div id="main-content" role="main">
        </div>

        <!-- fullscreen popup -->
        <div id="fullscreen-entry"></div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script src="<?= \helpers\View::getGlobalJsFileName(); ?>"></script>
</body>
</html>
